name: Node CI

on:
  push:
    branches:
      - master
  pull_request:  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: yarn
    - name: Run prettier
      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
    - name: Run test
      run: yarn test